export const GET_REQUEST_SUCCESS = 'GET_REQUEST_SUCCESS';
export const GET_REQUEST_FAILURE = 'GET_REQUEST_FAILURE';
export const SET_AMOUNT_CURRENCY = 'SET_AMOUNT_CURRENCY';
export const GET_EXCHANGE = 'GET_EXCHANGE';
export const SET_HISTORY_RECORD = 'SET_HISTORY_RECORD';